### ISSUE TITLE
In the starter Kit the file name is : AiPluginJson.cs and not appsettings.cs

### ISSUE THREAD

**Issue by dipteshbosedxc** [microsoft/semantic-kernel-starters#53]
**Describe the bug**
[A clear and concise description of what the bug is.](https://learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/chatgpt-plugins#:~:text=Open%20the%20appsettings.cs%20file.)

In the starter Kit the file name is : AiPluginJson.cs and not appsettings.cs

**To Reproduce**
1. Go to '(https://learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/chatgpt-plugins#:~:text=Open%20the%20appsettings.cs%20file.)'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by dipteshbosedxc** [comment]
Sorry the file name is appsettings.json and not appsettings.cs

**Comment by matthewbolanos** [comment]
Thanks! I've gone ahead and fixed this :)
