### ISSUE TITLE
Add troubleshooting info to starters when endpoint type doesn't match model

### ISSUE THREAD

**Issue by hario90** [microsoft/semantic-kernel-starters#65]
Update the README files of all starters on how to set the endpoint type in the case that the model doesn't match the default endpoint type. Also add troubleshooting information for the error described in [this issue](https://github.com/microsoft/semantic-kernel/issues/1564).

**Comment by parthM9** [comment]
Hi, I was wondering, is the log probs feature working for you? I am similarly using Semantic Kernel with Open AI 3.5 turbo and currently I am not able to access/use log probs feature. Thank you.

**Comment by hario90** [comment]
Hi @parthM9, I'm not familiar with the log probs feature. Is this a feature in the SDK or one of the starter projects?

**Comment by parthM9** [comment]
ah ok, Thanks for the confirmation. I thought it might be semantic kernel that is not supporting them for some reason.

**Comment by hario90** [comment]
Forgot to link the PR to the issue. This PR fixes this issue: https://github.com/microsoft/semantic-kernel-starters/pull/66
